# Template from: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogdc-service-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: ogdc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ogdc-service
  template:
    metadata:
      labels:
        app: ogdc-service
    spec:
      containers:
      - name: ogdc-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
          - "bash"
          - "-c"
          - "{{ .Values.ogdc_service_command }}"
        ports:
        - containerPort: 8000
          name: ogdc-api-port
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-api-secrets"
        env:
        - name: "ENVIRONMENT"
          value: {{ .Values.environment }}
        - name: "OGDC_RUNNER_IMAGE_TAG"
          value: {{ .Values.image.tag }}
        - name: "ARGO_WORKFLOWS_SERVICE_URL"
          # http://qgnet-ogdc-argo-workflows-server.qgnet.svc.cluster.local:2746
          value: "http://{{ .Release.Name }}-argo-workflows-server.{{ .Release.Namespace }}.svc.cluster.local:2746"
        # OGDC DB username/password
        - name: OGDC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: "ogdc-db-postgres-secrets"
              key: username
        - name: OGDC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "ogdc-db-postgres-secrets"
              key: password
        - name: S3_SECRET_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-secrets"
              key: rootUser
        - name: S3_SECRET_KEY_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-secrets"
              key: rootPassword
