
######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your passwords, then install them in your cluster. 
# `kubectl apply -n "$NAMESPACE" -f helm/admin/postgres-secrets.yaml`
apiVersion: v1
kind: Secret
metadata:
  # NOTE: `ogdc-db` is the expected release name of the CNPG postgres DB cluster
  # for the OGDC.
  name: ogdc-db-postgres-secrets

type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: password # required field for kubernetes.io/basic-auth
